export const SET_SHARED_IFRAME_STATE = 'SET_SHARED_IFRAME_STATE';
export const RESET_SHARED_IFRAME_STATE = 'RESET_SHARED_IFRAME_STATE';
export const SET_SHARED_IFRAME_ACTIVE = 'SET_SHARED_IFRAME_ACTIVE';
export const SET_WAS_ACTIVE_BEFORE_SCREENSHARE = 'SET_WAS_ACTIVE_BEFORE_SCREENSHARE';


